name: Python

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Cache Python
        id: cache-python
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: |
            ~/.cache/pip
            venv
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Virtualenv
        run: |
          python3 -m pip install --upgrade pip virtualenv
          virtualenv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          which python3
          which python
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements.txt

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -v