name: All

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Cache Python
        id: cache-python
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: |
            ~/.cache/pip
            venv
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install Virtualenv
        run: |
          python3 -m pip install --upgrade pip virtualenv
          pwd
          virtualenv venv

      - name: Install dependencies
        run: |
          pwd
          source venv/bin/activate
          which python3
          which python
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements.txt

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -v

      - name: Cache Node
        id: cache-node
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-node-${{ hashFiles('package*json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Node dependencies
        working-directory: 
        run: npm install

      - name: Some checks
        run: |
          node -v
          npm --version