name: Python

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node
        id: cache-node
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-node-${{ hashFiles('package*json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Node dependencies
        working-directory: 
        run: npm install

      - name: Some checks
        run: node -v